[package]
name = "artemis-uniffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "artemis"

[dependencies]
artemis = { path = "../artemis-core", features = ["full"] }
artemis-providers = { path = "../artemis-providers" }
jni = "0.22.4"
rustls-platform-verifier = { version = "0.7.0", features = ["jni"] }
uniffi = { version = "0.32.0", features = ["cli", "tokio"] }

[build-dependencies]
uniffi = { version = "0.32.0", features = ["build"] }
