[package]
name = "artemis-providers"
version = "0.1.0"
edition = "2024"

[dependencies]
artemis = { path = "../artemis-core", default-features = false }
futures = "0.3.32"
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
time = "0.3.53"

[lints]
workspace = true
